### ISSUE TITLE
Start months at 1, not zero

### ISSUE THREAD

**Issue by benknight** [arshaw/xdate#29]
I always forget that that the months are number 0-11 instead of 1-12.  It's totally unnatural to write April 1st, 2015 as `2015, 3, 1`.  Also, shouldn't days also be zero-index if months are too?  IMO the parameters should match how humans write dates.

**Comment by benknight** [comment]
Never mind, I'm realizing that matches `Date`'s implementation, and the point of this library is to wrap `Date`.  D'oh!  Closing.

**Comment by arshaw** [comment]
xdate just mimicked how the native javascript date object does it

**Comment by arshaw** [comment]
got it
