### ISSUE TITLE
XDate raises errors in Ecmascript 3-compliant engines

### ISSUE THREAD

**Issue by contentfree** [arshaw/xdate#33]
Using XDate 0.8 and Adobe's ExtendScript ("The After Effects scripting engine supports the 3rd Edition of the ECMA-262 Standard"), the following error is raised when loading the library:

`Error: Object of type Date found where a Number, Array, or Property is needed`

This is due to syntax like https://github.com/arshaw/xdate/blob/master/src/xdate.js#L109 where it tries to use the `+` shorthand instead of `Date#getTime()` (and Date instances should have their own if-branch since the `+` shorthand would work if `arg` is a number).

**Comment by contentfree** [comment]
Same issue exists at https://github.com/arshaw/xdate/blob/master/src/xdate.js#L157, https://github.com/arshaw/xdate/blob/master/src/xdate.js#L378, https://github.com/arshaw/xdate/blob/master/src/xdate.js#L438, https://github.com/arshaw/xdate/blob/master/src/xdate.js#L654, https://github.com/arshaw/xdate/blob/master/src/xdate.js#L669, and https://github.com/arshaw/xdate/blob/master/src/xdate.js#L700.

All of the above can be replaced with `.getTime()`, I'm pretty sure.

**Comment by arshaw** [comment]
Thanks for the hard work of tracking these down. Any way you could throw up a PR?

**Comment by contentfree** [comment]
Sorry for the delay, but here's the PR (#34)
