### ISSUE TITLE
Please add license line to package.json 

### ISSUE THREAD

**Issue by mikezerosix** [arshaw/xdate#47]
As you do not have the standard LICENSE.txt file nor the license key in package.json the automatic license checkers can not detect the license for your package. So would be nice to have the the standard license information tag, so it can be processed by the scanners.  

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license

The value can be what ever you want, like for example :
"Dual-licensed under MIT or GPL"

**Comment by jhbeskow** [comment]
I second this.  As it sits right now, the licensing is confusing and can cause license compliance issues for closed source applications.  Your website states that it is dual licensed, but that cannot verified via a license scan.
