### ISSUE TITLE
Vulnerability reported with xdate 0.8.2

### ISSUE THREAD

**Issue by rmn183** [arshaw/xdate#50]
Information
The GNU GPL is the most widely used free software license and has a strong copyleft requirement. When distributing derived works, the source code of the work must be made available under the same license. There are multiple variants of the GNU GPL, each with different requirements.

Can someone resolve this ?

**Comment by arshaw** [comment]
https://github.com/arshaw/xdate/pull/49#issuecomment-1970525494
